### ISSUE TITLE
Import into Angular

### ISSUE THREAD

**Issue by danielfrunza** [xaviergonz/js-angusj-clipper#13]
"ReferenceError: process is not defined" when try to "loadNativeClipperLibInstanceAsync" at:

var devMode = typeof "process" !== "undefined" && process.env && process.env.NODE_ENV !== "production";
in
(clipFunctions.js:7)

**Comment by xaviergonz** [comment]
Try import * as clipperLib from "js-angusj-clipper/dist/web"

See https://github.com/xaviergonz/js-angusj-clipper/issues/2

**Comment by anlumo** [comment]
I think the reason for this issue is that `typeof "process"` is a string, which is never undefined. Some JS preprocessors catch this and just remove the check.

**Comment by blayzen-w** [comment]
I ran into this same issue using webpack with the web version and had to manually define process on the window in order to get it to work. I'm also using the exact same import as @xaviergonz mentioned. It would be nice to see this fixed.

**Comment by xaviergonz** [comment]
> I can provide a small example project demonstrating the problem if needed.

that would be really helpful

**Comment by blayzen-w** [comment]
https://github.com/blayzen-w/clipper-process-undefined

**Comment by xaviergonz** [comment]
I just tested and it seems to work ok now (I changed the emscripten build type a few weeks ago), so closing :)

**Comment by blayzen-w** [comment]
Awesome! Thanks for working on it
