### ISSUE TITLE
Typescript type SubjectInput not exported

### ISSUE THREAD

**Issue by cmidgley** [xaviergonz/js-angusj-clipper#27]
The type `SubjectInput` is not being exported from the wrapper (its buddy `ClipInput` is exported).   Hand editing `index.d.ts` to include the import:

```ts
import { ClipInput, ClipParams, SubjectInput } from "./clipFunctions";
```

and then exporting it:

```ts
export { ClipType, EndType, JoinType, PolyFillType, NativeClipperLibLoadedFormat, NativeClipperLibRequestedFormat, PointInPolygonResult, PolyNode, PolyTree, IntPoint, IntRect, Path, ReadonlyPath, Paths, ReadonlyPaths, ClipInput, ClipParams, OffsetInput, OffsetParams, ClipperError , SubjectInput };
```

Resolves the issue.    Similar changes to `index.ts` would likely (correctly) fix this issue.

**Comment by xaviergonz** [comment]
Thanks! It should be exported in v1.3.0

Feel free to reopen the issue if something is wrong!
