### ISSUE TITLE
It seems that you can use floating point numbers

### ISSUE THREAD

**Issue by FishOrBear** [xaviergonz/js-angusj-clipper#6]
I found that when I use floating point numbers, I can also return the correct result.
I currently use the following functions: minkowskiSumPath and clipToPaths.

In addition, I feel that more detailed data is needed to explain how the wasm version should be used when the polyline is complex.

**Comment by FishOrBear** [comment]
no

**Comment by xaviergonz** [comment]
Sorry, I missed this issue. "no" means floating point numbers cannot be used and they have to be integers in the end?
