### ISSUE TITLE
Error when using preserveCollinear, etc, in ClipParams

### ISSUE THREAD

**Issue by pentacular** [xaviergonz/js-angusj-clipper#9]
When using preserveCollinear: true, strictlySimple: true, etc, I'm getting the following error. 

 TypeError {
    message: 'Cannot convert "0[object Object]" to int',
  }

Any idea what's going wrong?

**Comment by xaviergonz** [comment]
Do you have any sample code?

**Comment by pentacular** [comment]
import {
  ClipType,
  NativeClipperLibRequestedFormat,
  PolyFillType,
  loadNativeClipperLibInstanceAsync
} from 'js-angusj-clipper/web';

import test from 'ava';

test('strictlySimple', async t => {
  const clipper = await loadNativeClipperLibInstanceAsync(NativeClipperLibRequestedFormat.WasmOnly);
  const request =
    {
      clipType: ClipType.Union,
      subjectInputs: [{ data: [{ x: 50, y: 50 }, { x: -50, y: 50 }, { x: -50, y: -50 }, { x: 50, y: -50 }], closed: true },
                      { data: [{ x: -5, y: -5 }, { x: -5, y: 5 }, { x: 5, y: 5 }, { x: 5, y: -5 }], closed: true }],
      subjectFillType: PolyFillType.NonZero,
      strictlySimple: true
    };
  const result = clipper.clipToPolyTree(request);
  t.deepEqual(result, []);
});

reproduces the problem for me.

**Comment by xaviergonz** [comment]
Released as 1.0.4
